version: "3"

services:

  #
  # Database
  #
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  adminer:
    depends_on:
      - database
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  #
  # API
  #
  api:
    depends_on:
      - database
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_PASSWORD}
    ports:
      - ${DIRECTUS_API_PORT}:80
    networks:
      - backend

  #
  # Dashboard
  #
  app:
    depends_on:
      - database
      - api
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - ${DIRECTUS_APP_PORT}:80
    networks:
      - backend

networks:
  backend: